name: 電子閨蜜 测试

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 安装 pytest
        run: pip install pytest

      - name: 运行测试
        run: pytest -v test_電子閨蜜.py
